using Felna.Browser.DocumentParsers.TextReferences;

namespace Felna.Browser.DocumentParsers.Tests.HtmlTokenGeneratorTests;

[TestClass]
public class MarkupDeclarationTests
{
    [TestMethod]
    [DataRow("<!DOCTYPE h", @"[{""type"":""doctype"",""name"":""h"",""forcequirks"":true}]")]
    [DataRow("<!DOCTYPE ht", @"[{""type"":""doctype"",""name"":""ht"",""forcequirks"":true}]")]
    [DataRow("<!DOCTYPE htm", @"[{""type"":""doctype"",""name"":""htm"",""forcequirks"":true}]")]
    [DataRow("<!DOCTYPE html", @"[{""type"":""doctype"",""name"":""html"",""forcequirks"":true}]")]
    [DataRow("<!DOCTYPE html ", @"[{""type"":""doctype"",""name"":""html"",""forcequirks"":true}]")]
    [DataRow("<!DOCTYPE HTML>", @"[{""type"":""doctype"",""name"":""html""}]")]
    [DataRow("<!DOCTYPE html>", @"[{""type"":""doctype"",""name"":""html""}]")]
    [DataRow("<!doctype HTML>", @"[{""type"":""doctype"",""name"":""html""}]")]
    [DataRow("<!doctype html>", @"[{""type"":""doctype"",""name"":""html""}]")]
    [DataRow("<!DOCTYPE  HTML>", @"[{""type"":""doctype"",""name"":""html""}]")]
    [DataRow("<!DOCTYPE  html>", @"[{""type"":""doctype"",""name"":""html""}]")]
    [DataRow("<!doctype  HTML>", @"[{""type"":""doctype"",""name"":""html""}]")]
    [DataRow("<!doctype  html>", @"[{""type"":""doctype"",""name"":""html""}]")]
    [DataRow("<!DOCTYPE HTML >", @"[{""type"":""doctype"",""name"":""html""}]")]
    [DataRow("<!DOCTYPE html >", @"[{""type"":""doctype"",""name"":""html""}]")]
    [DataRow("<!doctype HTML >", @"[{""type"":""doctype"",""name"":""html""}]")]
    [DataRow("<!doctype html >", @"[{""type"":""doctype"",""name"":""html""}]")]
    [DataRow("<!DOCTYPE ht\u0000ml>", "[{\"type\":\"doctype\",\"name\":\"ht\ufffdml\"}]")]
    [DataRow("<!doctype html test", @"[{""type"":""doctype"",""name"":""html"",""forcequirks"":true}]")]
    [DataRow("<!doctype html test>", @"[{""type"":""doctype"",""name"":""html"",""forcequirks"":true}]")]
    [DataRow("<!doctype html test >", @"[{""type"":""doctype"",""name"":""html"",""forcequirks"":true}]")]
    [DataRow("<!doctype html test \u0000", @"[{""type"":""doctype"",""name"":""html"",""forcequirks"":true}]")]
    [DataRow("<!doctype html public id", @"[{""type"":""doctype"",""name"":""html"",""forcequirks"":true}]")]
    [DataRow("<!doctype html public", @"[{""type"":""doctype"",""name"":""html"",""forcequirks"":true}]")]
    [DataRow("<!doctype html public>", @"[{""type"":""doctype"",""name"":""html"",""forcequirks"":true}]")]
    [DataRow("<!doctype html system id", @"[{""type"":""doctype"",""name"":""html"",""forcequirks"":true}]")]
    [DataRow("<!doctype html system", @"[{""type"":""doctype"",""name"":""html"",""forcequirks"":true}]")]
    [DataRow("<!doctype html system>", @"[{""type"":""doctype"",""name"":""html"",""forcequirks"":true}]")]
    [DataRow("<!doctype html public \"pid\"", @"[{""type"":""doctype"",""name"":""html"",""publicidentifier"":""pid"",""forcequirks"":true}]")]
    [DataRow("<!doctype html public \"pid\" ", @"[{""type"":""doctype"",""name"":""html"",""publicidentifier"":""pid"",""forcequirks"":true}]")]
    [DataRow("<!doctype html public \"pid\">", @"[{""type"":""doctype"",""name"":""html"",""publicidentifier"":""pid""}]")]
    [DataRow("<!doctype html public \"pid\" >", @"[{""type"":""doctype"",""name"":""html"",""publicidentifier"":""pid""}]")]
    [DataRow("<!doctype html public 'pid'", @"[{""type"":""doctype"",""name"":""html"",""publicidentifier"":""pid"",""forcequirks"":true}]")]
    [DataRow("<!doctype html public 'pid' ", @"[{""type"":""doctype"",""name"":""html"",""publicidentifier"":""pid"",""forcequirks"":true}]")]
    [DataRow("<!doctype html public 'pid'>", @"[{""type"":""doctype"",""name"":""html"",""publicidentifier"":""pid""}]")]
    [DataRow("<!doctype html public 'pid' >", @"[{""type"":""doctype"",""name"":""html"",""publicidentifier"":""pid""}]")]
    [DataRow("<!doctype html public \"pid\" \"sid\"", @"[{""type"":""doctype"",""name"":""html"",""publicidentifier"":""pid"",""systemidentifier"":""sid"",""forcequirks"":true}]")]
    [DataRow("<!doctype html public \"pid\" \"sid\" ", @"[{""type"":""doctype"",""name"":""html"",""publicidentifier"":""pid"",""systemidentifier"":""sid"",""forcequirks"":true}]")]
    [DataRow("<!doctype html public \"pid\" \"sid\">", @"[{""type"":""doctype"",""name"":""html"",""publicidentifier"":""pid"",""systemidentifier"":""sid""}]")]
    [DataRow("<!doctype html public \"pid\" \"sid\" >", @"[{""type"":""doctype"",""name"":""html"",""publicidentifier"":""pid"",""systemidentifier"":""sid""}]")]
    [DataRow("<!doctype html public 'pid' 'sid'", @"[{""type"":""doctype"",""name"":""html"",""publicidentifier"":""pid"",""systemidentifier"":""sid"",""forcequirks"":true}]")]
    [DataRow("<!doctype html public 'pid' 'sid' ", @"[{""type"":""doctype"",""name"":""html"",""publicidentifier"":""pid"",""systemidentifier"":""sid"",""forcequirks"":true}]")]
    [DataRow("<!doctype html public 'pid' 'sid'>", @"[{""type"":""doctype"",""name"":""html"",""publicidentifier"":""pid"",""systemidentifier"":""sid""}]")]
    [DataRow("<!doctype html public 'pid' 'sid' >", @"[{""type"":""doctype"",""name"":""html"",""publicidentifier"":""pid"",""systemidentifier"":""sid""}]")]
    [DataRow("<!doctype html public \"pid\" 'sid'", @"[{""type"":""doctype"",""name"":""html"",""publicidentifier"":""pid"",""systemidentifier"":""sid"",""forcequirks"":true}]")]
    [DataRow("<!doctype html public \"pid\" 'sid' ", @"[{""type"":""doctype"",""name"":""html"",""publicidentifier"":""pid"",""systemidentifier"":""sid"",""forcequirks"":true}]")]
    [DataRow("<!doctype html public \"pid\" 'sid'>", @"[{""type"":""doctype"",""name"":""html"",""publicidentifier"":""pid"",""systemidentifier"":""sid""}]")]
    [DataRow("<!doctype html public \"pid\" 'sid' >", @"[{""type"":""doctype"",""name"":""html"",""publicidentifier"":""pid"",""systemidentifier"":""sid""}]")]
    [DataRow("<!doctype html public 'pid' \"sid\"", @"[{""type"":""doctype"",""name"":""html"",""publicidentifier"":""pid"",""systemidentifier"":""sid"",""forcequirks"":true}]")]
    [DataRow("<!doctype html public 'pid' \"sid\" ", @"[{""type"":""doctype"",""name"":""html"",""publicidentifier"":""pid"",""systemidentifier"":""sid"",""forcequirks"":true}]")]
    [DataRow("<!doctype html public 'pid' \"sid\">", @"[{""type"":""doctype"",""name"":""html"",""publicidentifier"":""pid"",""systemidentifier"":""sid""}]")]
    [DataRow("<!doctype html public 'pid' \"sid\" >", @"[{""type"":""doctype"",""name"":""html"",""publicidentifier"":""pid"",""systemidentifier"":""sid""}]")]
    [DataRow("<!doctype html system \"sid\"", @"[{""type"":""doctype"",""name"":""html"",""systemidentifier"":""sid"",""forcequirks"":true}]")]
    [DataRow("<!doctype html system \"sid\" ", @"[{""type"":""doctype"",""name"":""html"",""systemidentifier"":""sid"",""forcequirks"":true}]")]
    [DataRow("<!doctype html system \"sid\">", @"[{""type"":""doctype"",""name"":""html"",""systemidentifier"":""sid""}]")]
    [DataRow("<!doctype html system \"sid\" >", @"[{""type"":""doctype"",""name"":""html"",""systemidentifier"":""sid""}]")]
    [DataRow("<!doctype html system 'sid'", @"[{""type"":""doctype"",""name"":""html"",""systemidentifier"":""sid"",""forcequirks"":true}]")]
    [DataRow("<!doctype html system 'sid' ", @"[{""type"":""doctype"",""name"":""html"",""systemidentifier"":""sid"",""forcequirks"":true}]")]
    [DataRow("<!doctype html system 'sid'>", @"[{""type"":""doctype"",""name"":""html"",""systemidentifier"":""sid""}]")]
    [DataRow("<!doctype html system 'sid' >", @"[{""type"":""doctype"",""name"":""html"",""systemidentifier"":""sid""}]")]
    public void GivenHtmlCorrectTokensGenerated(string html, string json)
    {
        var tokens = HtmlTokenGeneratorTestRunner.ConvertJsonToTokens(json);
        
        HtmlTokenGeneratorTestRunner.Run(html, tokens);
    }
}